# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_client(object):
    def setupUi(self, client):
        client.setObjectName("client")
        client.resize(2100, 1500)
        font = QtGui.QFont()
        font.setFamily("Arial")
        client.setFont(font)
        client.setStyleSheet(   
                "QWidget{ background:#e9e9e9 }"
        
                "QAbstractButton{ border-style:outset; border-radius:5px; border-color: #d3d3d3; padding:5px; color:#1a1a1a; background:#fafafa }"
                "QAbstractButton:hover{ color:#1a1a1a; background-color:#e8e8e8 }"
                "QAbstractButton:pressed{ color:#dcdcdc; background-color:#8a6353 }"
        
                "QLabel{ color:#1a1a1a }"
                "QLabel:focus{ border:1px solid #8a6353 }"
        
                "QLineEdit{ border:1px solid #d3d3d3; border-radius:5px; padding:2px; background:none; selection-background-color:#8a6353; selection-color:#dcdcdc }"
                "QLineEdit:focus,QLineEdit:hover{ border:1px solid #d3d3d3 }"
                "QLineEdit{ lineedit-password-character:9679 }"

                "QSlider::groove:horizontal,QSlider::add-page:horizontal{ height:3px; border-radius:3px; background:#fafafa }"
                "QSlider::sub-page:horizontal{ height:8px; border-radius:3px; background:#8a6353 }"
                "QSlider::handle:horizontal{ width:12px; margin-top:-5px; margin-bottom:-4px; border-radius:6px; background:qradialgradient(spread:pad,cx:0.5,cy:0.5,radius:0.5,fx:0.5,fy:0.5,stop:0.6 #8a6353,stop:0.8 #8a6353) }"
                "QSlider::groove:vertical,QSlider::sub-page:vertical{ width:3px; border-radius:3px; background:#fafafa }"
                "QSlider::add-page:vertical{ width:8px; border-radius:3px; background:#8a6353 }"
                "QSlider::handle:vertical{ height:12px; margin-left:-5px; margin-right:-4px; border-radius:6px; background:qradialgradient(spread:pad,cx:0.5,cy:0.5,radius:0.5,fx:0.5,fy:0.5,stop:0.6 #8a6353,stop:0.8 #8a6353) }"
        
                "QGroupBox::title { pading:2px; color:white; subcontrol-position: top center; border-top:0px ; background: transparent; }")
        client.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))

        font = QtGui.QFont()
        font.setFamily("Arial")

        # Video feed container
        self.Video = QtWidgets.QLabel(client)
        self.Video.setGeometry(QtCore.QRect(30, 30, 990, 810))
        self.Video.setFont(font)
        self.Video.setText("")
        self.Video.setObjectName("Video")

        # MOVEMENT CONTROLS
        # Head title
        self.label_head_title = QtWidgets.QLabel(client)
        self.label_head_title.setGeometry(QtCore.QRect(240, 1230, 120, 30))
        self.label_head_title.setFont(font)
        self.label_head_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_head_title.setObjectName("label_head_title")

        # Head sides slider and value
        # Vertical
        self.slider_head = QtWidgets.QSlider(client)
        self.slider_head.setGeometry(QtCore.QRect(420, 900, 60, 300))
        self.slider_head.setMaximum(180)
        self.slider_head.setProperty("value", 90)
        self.slider_head.setOrientation(QtCore.Qt.Vertical)
        self.slider_head.setObjectName("slider_head") 

        self.label_head = QtWidgets.QLabel(client)
        self.label_head.setGeometry(QtCore.QRect(300, 1200, 60, 30))
        self.label_head.setFont(font)
        self.label_head.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_head.setAlignment(QtCore.Qt.AlignCenter)
        self.label_head.setObjectName("label_head")

        # Horizontal
        self.slider_head_1 = QtWidgets.QSlider(client)
        self.slider_head_1.setGeometry(QtCore.QRect(150, 1170, 300, 60))
        self.slider_head_1.setMaximum(180)
        self.slider_head_1.setProperty("value", 90)
        self.slider_head_1.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.slider_head_1.setOrientation(QtCore.Qt.Horizontal)
        self.slider_head_1.setObjectName("slider_head_1")

        self.label_head_1 = QtWidgets.QLabel(client)
        self.label_head_1.setGeometry(QtCore.QRect(240, 1200, 60, 30))
        self.label_head_1.setFont(font)
        self.label_head_1.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_head_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_head_1.setObjectName("label_head_1")

        # Move label and value
        # The steering wheel is drawn and controlled in main.py
        self.label_move_title = QtWidgets.QLabel(client)
        self.label_move_title.setGeometry(QtCore.QRect(690, 1230, 120, 30))
        self.label_move_title.setFont(font)
        self.label_move_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_move_title.setObjectName("label_move_title")

        self.label_move_value = QtWidgets.QLabel(client)
        self.label_move_value.setGeometry(QtCore.QRect(690, 1200, 120, 30))
        self.label_move_value.setFont(font)
        self.label_move_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_move_value.setObjectName("label_move_value")

        # Height slider and its values
        self.label_height = QtWidgets.QLabel(client)
        self.label_height.setGeometry(QtCore.QRect(1110, 1230, 120, 30))
        self.label_height.setFont(font)
        self.label_height.setAlignment(QtCore.Qt.AlignCenter)
        self.label_height.setObjectName("label_height")

        self.slider_height = QtWidgets.QSlider(client)
        self.slider_height.setGeometry(QtCore.QRect(1140, 900, 60, 300))
        self.slider_height.setMinimum(-40)
        self.slider_height.setMaximum(40)
        self.slider_height.setOrientation(QtCore.Qt.Vertical)
        self.slider_height.setObjectName("slider_height")

        self.label_height_value = QtWidgets.QLabel(client)
        self.label_height_value.setGeometry(QtCore.QRect(1110, 1200, 120, 30))
        self.label_height_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_height_value.setFont(font)
        self.label_height_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_height_value.setObjectName("label_height_value")

        # Pane label and value
        # The pane control is drawn in main.py
        self.label_pane_title = QtWidgets.QLabel(client)
        self.label_pane_title.setGeometry(QtCore.QRect(1350, 1230, 120, 30))
        self.label_pane_title.setFont(font)
        self.label_pane_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pane_title.setObjectName("label_pane_title")
 
        self.label_pane_value = QtWidgets.QLabel(client)
        self.label_pane_value.setGeometry(QtCore.QRect(1350, 1200, 120, 30))
        self.label_pane_value.setFont(font)
        self.label_pane_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pane_value.setObjectName("label_pane_value")

        # Twist slider and it's labels
        self.label_twist_title = QtWidgets.QLabel(client)
        self.label_twist_title.setGeometry(QtCore.QRect(1590, 1230, 120, 30))
        self.label_twist_title.setFont(font)
        self.label_twist_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_twist_title.setObjectName("label_twist_title")

        self.slider_twist = QtWidgets.QSlider(client)
        self.slider_twist.setGeometry(QtCore.QRect(1620, 900, 60, 300))
        self.slider_twist.setMinimum(-20)
        self.slider_twist.setMaximum(20)
        self.slider_twist.setOrientation(QtCore.Qt.Vertical)
        self.slider_twist.setObjectName("slider_twist")

        self.label_twist_value = QtWidgets.QLabel(client)
        self.label_twist_value.setGeometry(QtCore.QRect(1590, 1200, 120, 30))
        self.label_twist_value.setFont(font)
        self.label_twist_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_twist_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_twist_value.setObjectName("label_twist_value")

        # Tilt label and value
        # The tilt control is drawn in main.py
        self.label_tilt_title = QtWidgets.QLabel(client)
        self.label_tilt_title.setGeometry(QtCore.QRect(1830, 1230, 120, 30))
        self.label_tilt_title.setFont(font)
        self.label_tilt_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tilt_title.setObjectName("label_tilt_title")

        self.label_tilt_value = QtWidgets.QLabel(client)
        self.label_tilt_value.setGeometry(QtCore.QRect(1830, 1200, 120, 30))
        self.label_tilt_value.setFont(font)
        self.label_tilt_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_tilt_value.setObjectName("label_tilt_value")

        # BUTTON CONTROLS
        # Connect button and IP address field
        self.Button_Connect = QtWidgets.QPushButton(client)
        self.Button_Connect.setGeometry(QtCore.QRect(30, 1380, 180, 30))
        self.Button_Connect.setFont(font)
        self.Button_Connect.setObjectName("Button_Connect")

        self.lineEdit_IP_Adress = QtWidgets.QLineEdit(client)
        self.lineEdit_IP_Adress.setGeometry(QtCore.QRect(240, 1380, 180, 30))
        self.lineEdit_IP_Adress.setFont(font)
        self.lineEdit_IP_Adress.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_IP_Adress.setObjectName("lineEdit_IP_Adress")

        # Calibration. Opens new window
        self.Button_Calibration = QtWidgets.QPushButton(client)
        self.Button_Calibration.setGeometry(QtCore.QRect(30, 1440, 180, 30))
        font.setBold(False)
        font.setWeight(50)
        self.Button_Calibration.setFont(font)
        self.Button_Calibration.setObjectName("Button_Calibration")

        # Gait mode - toggles run (three legs at a time) and walk (one leg at a time)
        self.layoutWidget1 = QtWidgets.QWidget(client)
        self.layoutWidget1.setGeometry(QtCore.QRect(450, 1380, 180, 90))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ButtonGaitMode1 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.ButtonGaitMode1.setFont(font)
        self.ButtonGaitMode1.setObjectName("ButtonGaitMode1")
        self.verticalLayout_2.addWidget(self.ButtonGaitMode1)
        self.ButtonGaitMode2 = QtWidgets.QRadioButton(self.layoutWidget1)
        self.ButtonGaitMode2.setFont(font)
        self.ButtonGaitMode2.setObjectName("ButtonGaitMode2")
        self.verticalLayout_2.addWidget(self.ButtonGaitMode2)

        # Speed slider, title and value
        self.label_speed_title = QtWidgets.QLabel(client)
        self.label_speed_title.setGeometry(QtCore.QRect(540, 1320, 90, 30))
        self.label_speed_title.setFont(font)
        self.label_speed_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_speed_title.setObjectName("label_speed_title")

        self.slider_speed = QtWidgets.QSlider(client)
        self.slider_speed.setGeometry(QtCore.QRect(690, 1320, 180, 60))
        self.slider_speed.setFont(font)
        self.slider_speed.setMinimum(2)
        self.slider_speed.setMaximum(10)
        self.slider_speed.setProperty("value", 8)
        self.slider_speed.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.slider_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_speed.setObjectName("slider_speed")

        self.label_speed = QtWidgets.QLabel(client)
        self.label_speed.setGeometry(QtCore.QRect(720, 1320, 120, 30))
        self.label_speed.setFont(font)
        self.label_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_speed.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_speed.setObjectName("label_speed")

        # Toggle between strafe and trun on keybaord and movement wheel
        self.layoutWidget = QtWidgets.QWidget(client)
        self.layoutWidget.setGeometry(QtCore.QRect(690, 1380, 180, 90))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonActionMode1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.ButtonActionMode1.setFont(font)
        self.ButtonActionMode1.setObjectName("ButtonActionMode1")
        self.verticalLayout.addWidget(self.ButtonActionMode1)
        self.ButtonActionMode2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.ButtonActionMode2.setFont(font)
        self.ButtonActionMode2.setObjectName("ButtonActionMode2")
        self.verticalLayout.addWidget(self.ButtonActionMode2)

        # Buzzer
        self.Button_Buzzer = QtWidgets.QPushButton(client)
        self.Button_Buzzer.setGeometry(QtCore.QRect(1140, 1320, 180, 30))
        self.Button_Buzzer.setFont(font)
        self.Button_Buzzer.setObjectName("Button_Buzzer")

        # Button for ultrasound obstacle detection and it's output
        self.Button_Sonic = QtWidgets.QPushButton(client)
        self.Button_Sonic.setGeometry(QtCore.QRect(1140, 1380, 180, 30))
        self.Button_Sonic.setFont(font)
        self.Button_Sonic.setObjectName("Button_Sonic")

        self.label_sonic = QtWidgets.QLabel(client)
        self.label_sonic.setGeometry(QtCore.QRect(1140, 1440, 180, 30))
        self.label_sonic.setFont(font)
        self.label_sonic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sonic.setObjectName("label_sonic")

        # LED Button. Opens new window
        self.Button_LED = QtWidgets.QPushButton(client)
        self.Button_LED.setGeometry(QtCore.QRect(1350, 1320, 180, 30))
        self.Button_LED.setFont(font)
        self.Button_LED.setObjectName("Button_LED")

        # Button labelled balance
        self.Button_IMU = QtWidgets.QPushButton(client)
        self.Button_IMU.setGeometry(QtCore.QRect(1350, 1380, 180, 30))
        self.Button_IMU.setFont(font)
        self.Button_IMU.setObjectName("Button_IMU")

        # Relax button
        self.Button_Relax = QtWidgets.QPushButton(client)
        self.Button_Relax.setGeometry(QtCore.QRect(1350, 1440, 180, 30))
        self.Button_Relax.setFont(font)
        self.Button_Relax.setObjectName("Button_Relax")

        # Opens video feed in the placeholder
        self.Button_Video = QtWidgets.QPushButton(client)
        self.Button_Video.setGeometry(QtCore.QRect(1560, 1320, 180, 30))
        font.setBold(False)
        font.setWeight(50)
        self.Button_Video.setFont(font)
        self.Button_Video.setObjectName("Button_Video")

        # Face recognition button
        self.Button_Face_Recognition = QtWidgets.QPushButton(client)
        self.Button_Face_Recognition.setGeometry(QtCore.QRect(1560, 1380, 180, 30))
        self.Button_Face_Recognition.setFont(font)
        self.Button_Face_Recognition.setObjectName("Button_Face_Recognition")
        
        # Face ID button
        self.Button_Face_ID = QtWidgets.QPushButton(client)
        self.Button_Face_ID.setGeometry(QtCore.QRect(1560, 1440, 180, 30))
        self.Button_Face_ID.setFont(font)
        self.Button_Face_ID.setObjectName("Button_Face_ID")

        # Electrical load indicator
        self.label_Load = QtWidgets.QLabel(client)
        self.label_Load.setGeometry(QtCore.QRect(1770, 1380, 90, 30))
        self.label_Load.setObjectName("label_Load")

        self.progress_Power1 = QtWidgets.QProgressBar(client)
        self.progress_Power1.setGeometry(QtCore.QRect(1890, 1380, 180, 30))
        self.progress_Power1.setStyleSheet(
                "QProgressBar::chunk { background-color:#08aaff; width: 20px } "
                "QProgressBar { border-style:outset; border-radius:2px; border-color: #d3d3d3; padding: 5px; background-color: #FFFFFF }"
                "QProgressBar { text-align: center; color: rgb(0,0,0) }")
        self.progress_Power1.setProperty("value", 100)
        self.progress_Power1.setFormat("")
        self.progress_Power1.setObjectName("progress_Power1")

        # Electrical Pi draw
        self.label_RasPi = QtWidgets.QLabel(client)
        self.label_RasPi.setGeometry(QtCore.QRect(1770, 1440, 90, 30))
        self.label_RasPi.setObjectName("label_RasPi")

        self.progress_Power2 = QtWidgets.QProgressBar(client)
        self.progress_Power2.setGeometry(QtCore.QRect(1890, 1440, 180, 30))
        self.progress_Power2.setStyleSheet(
                "QProgressBar::chunk { background-color:#26fa03; width: 20px; }"
                "QProgressBar { border-style:outset; border-radius:2px; border-color: #d3d3d3; padding: 5px; background-color: #FFFFFF }"
                "QProgressBar { text-align: center; color: rgb(0,0,0) }")
        self.progress_Power2.setProperty("value", 100)
        self.progress_Power2.setFormat("")
        self.progress_Power2.setObjectName("progress_Power2")

        # NEW FUNCTIONS
        # Attack button
        self.Button_Attack = QtWidgets.QPushButton(client)
        self.Button_Attack.setGeometry(QtCore.QRect(930, 1380, 180, 30))
        self.Button_Attack.setFont(font)
        self.Button_Attack.setObjectName("Button_Attack")

        #Dead button
        self.Button_Dead = QtWidgets.QPushButton(client)
        self.Button_Dead.setGeometry(QtCore.QRect(930, 1440, 180, 30))
        self.Button_Dead.setFont(font)
        self.Button_Dead.setObjectName("Button_Dead")

        # Detailed control
        # Leg title labels
        self.label_leg1_title = QtWidgets.QLabel(client)
        self.label_leg1_title.setGeometry(QtCore.QRect(1350, 240, 90, 60))
        self.label_leg1_title.setFont(font)
        self.label_leg1_title.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg1_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg1_title.setObjectName("label_leg1_title")

        self.label_leg2_title = QtWidgets.QLabel(client)
        self.label_leg2_title.setGeometry(QtCore.QRect(1290, 510, 90, 60))
        self.label_leg2_title.setFont(font)
        self.label_leg2_title.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg2_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg2_title.setObjectName("label_leg2_title")

        self.label_leg3_title = QtWidgets.QLabel(client)
        self.label_leg3_title.setGeometry(QtCore.QRect(1530, 780, 90, 60))
        self.label_leg3_title.setFont(font)
        self.label_leg3_title.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg3_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg3_title.setObjectName("label_leg3_title")

        self.label_leg4_title = QtWidgets.QLabel(client)
        self.label_leg4_title.setGeometry(QtCore.QRect(1680, 780, 90, 60))
        self.label_leg4_title.setFont(font)
        self.label_leg4_title.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg4_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg4_title.setObjectName("label_leg4_title")

        self.label_leg5_title = QtWidgets.QLabel(client)
        self.label_leg5_title.setGeometry(QtCore.QRect(1920, 510, 90, 60))
        self.label_leg5_title.setFont(font)
        self.label_leg5_title.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg5_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg5_title.setObjectName("label_leg5_title")

        self.label_leg6_title = QtWidgets.QLabel(client)
        self.label_leg6_title.setGeometry(QtCore.QRect(1860, 240, 90, 60))
        self.label_leg6_title.setFont(font)
        self.label_leg6_title.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg6_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg6_title.setObjectName("label_leg6_title")

        #Step controls
        self.label_step_title = QtWidgets.QLabel(client)
        self.label_step_title.setGeometry(QtCore.QRect(1500, 60, 90, 30))
        self.label_step_title.setFont(font)
        self.label_step_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step_title.setObjectName("label_step_title")

        self.slider_step = QtWidgets.QSlider(client)
        self.slider_step.setGeometry(QtCore.QRect(1620, 60, 180, 60))
        self.slider_step.setFont(font)
        self.slider_step.setMinimum(1)
        self.slider_step.setMaximum(15)
        self.slider_step.setProperty("value", 5)
        self.slider_step.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.slider_step.setOrientation(QtCore.Qt.Horizontal)
        self.slider_step.setObjectName("slider_step")

        self.label_step_value = QtWidgets.QLabel(client)
        self.label_step_value.setGeometry(QtCore.QRect(1650, 60, 120, 30))
        self.label_step_value.setFont(font)
        self.label_step_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_step_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_step_value.setObjectName("label_step_value")

        #Servo Angle Values
        #Leg 1
        self.label_leg1_front_value = QtWidgets.QLabel(client)
        self.label_leg1_front_value.setGeometry(QtCore.QRect(1320, 90, 60, 60))
        self.label_leg1_front_value.setFont(font)
        self.label_leg1_front_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg1_front_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg1_front_value.setObjectName("label_leg1_front_value")

        self.label_leg1_middle_value = QtWidgets.QLabel(client)
        self.label_leg1_middle_value.setGeometry(QtCore.QRect(1440, 120, 60, 60))
        self.label_leg1_middle_value.setFont(font)
        self.label_leg1_middle_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg1_middle_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg1_middle_value.setObjectName("label_leg1_middle_value")

        self.label_leg1_back_value = QtWidgets.QLabel(client)
        self.label_leg1_back_value.setGeometry(QtCore.QRect(1470, 240, 60, 60))
        self.label_leg1_back_value.setFont(font)
        self.label_leg1_back_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg1_back_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg1_back_value.setObjectName("label_leg1_back_value")

        #Leg 2
        self.label_leg2_front_value = QtWidgets.QLabel(client)
        self.label_leg2_front_value.setGeometry(QtCore.QRect(1290, 390, 60, 60))
        self.label_leg2_front_value.setFont(font)
        self.label_leg2_front_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg2_front_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg2_front_value.setObjectName("label_leg2_front_value")

        self.label_leg2_middle_value = QtWidgets.QLabel(client)
        self.label_leg2_middle_value.setGeometry(QtCore.QRect(1410, 450, 60, 60))
        self.label_leg2_middle_value.setFont(font)
        self.label_leg2_middle_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg2_middle_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg2_middle_value.setObjectName("label_leg2_middle_value")

        self.label_leg2_back_value = QtWidgets.QLabel(client)
        self.label_leg2_back_value.setGeometry(QtCore.QRect(1530, 390, 60, 60))
        self.label_leg2_back_value.setFont(font)
        self.label_leg2_back_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg2_back_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg2_back_value.setObjectName("label_leg2_back_value")

        #Leg 3
        self.label_leg3_front_value = QtWidgets.QLabel(client)
        self.label_leg3_front_value.setGeometry(QtCore.QRect(1320, 750, 60, 60))
        self.label_leg3_front_value.setFont(font)
        self.label_leg3_front_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg3_front_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg3_front_value.setObjectName("label_leg3_front_value")

        self.label_leg3_middle_value = QtWidgets.QLabel(client)
        self.label_leg3_middle_value.setGeometry(QtCore.QRect(1440, 720, 60, 60))
        self.label_leg3_middle_value.setFont(font)
        self.label_leg3_middle_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg3_middle_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg3_middle_value.setObjectName("label_leg3_middle_value")

        self.label_leg3_back_value = QtWidgets.QLabel(client)
        self.label_leg3_back_value.setGeometry(QtCore.QRect(1470, 600, 60, 60))
        self.label_leg3_back_value.setFont(font)
        self.label_leg3_back_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg3_back_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg3_back_value.setObjectName("label_leg3_back_value")

        #Leg 4
        self.label_leg4_front_value = QtWidgets.QLabel(client)
        self.label_leg4_front_value.setGeometry(QtCore.QRect(1920, 750, 60, 60))
        self.label_leg4_front_value.setFont(font)
        self.label_leg4_front_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg4_front_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg4_front_value.setObjectName("label_leg4_front_value")

        self.label_leg4_middle_value = QtWidgets.QLabel(client)
        self.label_leg4_middle_value.setGeometry(QtCore.QRect(1800, 720, 60, 60))
        self.label_leg4_middle_value.setFont(font)
        self.label_leg4_middle_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg4_middle_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg4_middle_value.setObjectName("label_leg4_middle_value")

        self.label_leg4_back_value = QtWidgets.QLabel(client)
        self.label_leg4_back_value.setGeometry(QtCore.QRect(1770, 600, 60, 60))
        self.label_leg4_back_value.setFont(font)
        self.label_leg4_back_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg4_back_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg4_back_value.setObjectName("label_leg4_back_value")

        #Leg 5
        self.label_leg5_front_value = QtWidgets.QLabel(client)
        self.label_leg5_front_value.setGeometry(QtCore.QRect(1950, 390, 60, 60))
        self.label_leg5_front_value.setFont(font)
        self.label_leg5_front_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg5_front_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg5_front_value.setObjectName("label_leg5_front_value")

        self.label_leg5_middle_value = QtWidgets.QLabel(client)
        self.label_leg5_middle_value.setGeometry(QtCore.QRect(1830, 450, 60, 60))
        self.label_leg5_middle_value.setFont(font)
        self.label_leg5_middle_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg5_middle_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg5_middle_value.setObjectName("label_leg5_middle_value")

        self.label_leg5_back_value = QtWidgets.QLabel(client)
        self.label_leg5_back_value.setGeometry(QtCore.QRect(1710, 390, 60, 60))
        self.label_leg5_back_value.setFont(font)
        self.label_leg5_back_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg5_back_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg5_back_value.setObjectName("label_leg5_back_value")

        #Leg 6
        self.label_leg6_front_value = QtWidgets.QLabel(client)
        self.label_leg6_front_value.setGeometry(QtCore.QRect(1920, 90, 60, 60))
        self.label_leg6_front_value.setFont(font)
        self.label_leg6_front_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg6_front_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg6_front_value.setObjectName("label_leg6_front_value")

        self.label_leg6_middle_value = QtWidgets.QLabel(client)
        self.label_leg6_middle_value.setGeometry(QtCore.QRect(1800, 120, 60, 60))
        self.label_leg6_middle_value.setFont(font)
        self.label_leg6_middle_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg6_middle_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg6_middle_value.setObjectName("label_leg6_middle_value")

        self.label_leg6_back_value = QtWidgets.QLabel(client)
        self.label_leg6_back_value.setGeometry(QtCore.QRect(1770, 240, 60, 60))
        self.label_leg6_back_value.setFont(font)
        self.label_leg6_back_value.setStyleSheet("background-color: rgba(0,0,0,0%)")
        self.label_leg6_back_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_leg6_back_value.setObjectName("label_leg6_back_value")

        # Leg buttons
        # Leg 1
        self.button_leg1_front_plus = QtWidgets.QPushButton(client)
        self.button_leg1_front_plus.setGeometry(QtCore.QRect(1380, 60, 30, 60))
        self.button_leg1_front_plus.setFont(font)
        self.button_leg1_front_plus.setObjectName("button_leg1_front_plus")

        self.button_leg1_front_minus = QtWidgets.QPushButton(client)
        self.button_leg1_front_minus.setGeometry(QtCore.QRect(1380, 120, 30, 60))
        self.button_leg1_front_minus.setFont(font)
        self.button_leg1_front_minus.setObjectName("button_leg1_front_minus")

        self.button_leg1_middle_plus = QtWidgets.QPushButton(client)
        self.button_leg1_middle_plus.setGeometry(QtCore.QRect(1410, 180, 60, 30))
        self.button_leg1_middle_plus.setFont(font)
        self.button_leg1_middle_plus.setObjectName("button_leg1_middle_plus")

        self.button_leg1_middle_minus = QtWidgets.QPushButton(client)
        self.button_leg1_middle_minus.setGeometry(QtCore.QRect(1470, 180, 60, 30))
        self.button_leg1_middle_minus.setFont(font)
        self.button_leg1_middle_minus.setObjectName("button_leg1_middle_minus")

        self.button_leg1_back_plus = QtWidgets.QPushButton(client)
        self.button_leg1_back_plus.setGeometry(QtCore.QRect(1530, 210, 30, 60))
        self.button_leg1_back_plus.setFont(font)
        self.button_leg1_back_plus.setObjectName("button_leg1_back_plus")

        self.button_leg1_back_minus = QtWidgets.QPushButton(client)
        self.button_leg1_back_minus.setGeometry(QtCore.QRect(1530, 270, 30, 60))
        self.button_leg1_back_minus.setFont(font)
        self.button_leg1_back_minus.setObjectName("button_leg1_back_minus")

        # Leg 2
        self.button_leg2_front_plus = QtWidgets.QPushButton(client)
        self.button_leg2_front_plus.setGeometry(QtCore.QRect(1260, 450, 60, 30))
        self.button_leg2_front_plus.setFont(font)
        self.button_leg2_front_plus.setObjectName("button_leg2_front_plus")

        self.button_leg2_front_minus = QtWidgets.QPushButton(client)
        self.button_leg2_front_minus.setGeometry(QtCore.QRect(1320, 450, 60, 30))
        self.button_leg2_front_minus.setFont(font)
        self.button_leg2_front_minus.setObjectName("button_leg2_front_minus")

        self.button_leg2_middle_plus = QtWidgets.QPushButton(client)
        self.button_leg2_middle_plus.setGeometry(QtCore.QRect(1380, 420, 60, 30))
        self.button_leg2_middle_plus.setFont(font)
        self.button_leg2_middle_plus.setObjectName("button_leg2_middle_plus")

        self.button_leg2_middle_minus = QtWidgets.QPushButton(client)
        self.button_leg2_middle_minus.setGeometry(QtCore.QRect(1440, 420, 60, 30))
        self.button_leg2_middle_minus.setFont(font)
        self.button_leg2_middle_minus.setObjectName("button_leg2_middle_minus")

        self.button_leg2_back_plus = QtWidgets.QPushButton(client)
        self.button_leg2_back_plus.setGeometry(QtCore.QRect(1500, 450, 60, 30))
        self.button_leg2_back_plus.setFont(font)
        self.button_leg2_back_plus.setObjectName("button_leg2_back_plus")

        self.button_leg2_back_minus = QtWidgets.QPushButton(client)
        self.button_leg2_back_minus.setGeometry(QtCore.QRect(1560, 450, 60, 30))
        self.button_leg2_back_minus.setFont(font)
        self.button_leg2_back_minus.setObjectName("button_leg2_back_minus")

        # Leg 3
        self.button_leg3_front_plus = QtWidgets.QPushButton(client)
        self.button_leg3_front_plus.setGeometry(QtCore.QRect(1380, 720, 30, 60))
        self.button_leg3_front_plus.setFont(font)
        self.button_leg3_front_plus.setObjectName("button_leg3_front_plus")

        self.button_leg3_front_minus = QtWidgets.QPushButton(client)
        self.button_leg3_front_minus.setGeometry(QtCore.QRect(1380, 780, 30, 60))
        self.button_leg3_front_minus.setFont(font)
        self.button_leg3_front_minus.setObjectName("button_leg3_front_minus")

        self.button_leg3_middle_plus = QtWidgets.QPushButton(client)
        self.button_leg3_middle_plus.setGeometry(QtCore.QRect(1410, 690, 60, 30))
        self.button_leg3_middle_plus.setFont(font)
        self.button_leg3_middle_plus.setObjectName("button_leg3_middle_plus")

        self.button_leg3_middle_minus = QtWidgets.QPushButton(client)
        self.button_leg3_middle_minus.setGeometry(QtCore.QRect(1470, 690, 60, 30))
        self.button_leg3_middle_minus.setFont(font)
        self.button_leg3_middle_minus.setObjectName("button_leg3_middle_minus")

        self.button_leg3_back_plus = QtWidgets.QPushButton(client)
        self.button_leg3_back_plus.setGeometry(QtCore.QRect(1530, 570, 30, 60))
        self.button_leg3_back_plus.setFont(font)
        self.button_leg3_back_plus.setObjectName("button_leg3_back_plus")

        self.button_leg3_back_minus = QtWidgets.QPushButton(client)
        self.button_leg3_back_minus.setGeometry(QtCore.QRect(1530, 630, 30, 60))
        self.button_leg3_back_minus.setFont(font)
        self.button_leg3_back_minus.setObjectName("button_leg3_back_minus")

        # Leg 4
        self.button_leg4_front_plus = QtWidgets.QPushButton(client)
        self.button_leg4_front_plus.setGeometry(QtCore.QRect(1890, 720, 30, 60))
        self.button_leg4_front_plus.setFont(font)
        self.button_leg4_front_plus.setObjectName("button_leg4_front_plus")

        self.button_leg4_front_minus = QtWidgets.QPushButton(client)
        self.button_leg4_front_minus.setGeometry(QtCore.QRect(1890, 780, 30, 60))
        self.button_leg4_front_minus.setFont(font)
        self.button_leg4_front_minus.setObjectName("button_leg4_front_minus")

        self.button_leg4_middle_plus = QtWidgets.QPushButton(client)
        self.button_leg4_middle_plus.setGeometry(QtCore.QRect(1770, 690, 60, 30))
        self.button_leg4_middle_plus.setFont(font)
        self.button_leg4_middle_plus.setObjectName("button_leg4_middle_plus")

        self.button_leg4_middle_minus = QtWidgets.QPushButton(client)
        self.button_leg4_middle_minus.setGeometry(QtCore.QRect(1830, 690, 60, 30))
        self.button_leg4_middle_minus.setFont(font)
        self.button_leg4_middle_minus.setObjectName("button_leg4_middle_minus")

        self.button_leg4_back_plus = QtWidgets.QPushButton(client)
        self.button_leg4_back_plus.setGeometry(QtCore.QRect(1740, 570, 30, 60))
        self.button_leg4_back_plus.setFont(font)
        self.button_leg4_back_plus.setObjectName("button_leg4_back_plus")

        self.button_leg4_back_minus = QtWidgets.QPushButton(client)
        self.button_leg4_back_minus.setGeometry(QtCore.QRect(1740, 630, 30, 60))
        self.button_leg4_back_minus.setFont(font)
        self.button_leg4_back_minus.setObjectName("button_leg4_back_minus")

        # Leg 5
        self.button_leg5_front_plus = QtWidgets.QPushButton(client)
        self.button_leg5_front_plus.setGeometry(QtCore.QRect(1680, 450, 60, 30))
        self.button_leg5_front_plus.setFont(font)
        self.button_leg5_front_plus.setObjectName("button_leg5_front_plus")

        self.button_leg5_front_minus = QtWidgets.QPushButton(client)
        self.button_leg5_front_minus.setGeometry(QtCore.QRect(1740, 450, 60, 30))
        self.button_leg5_front_minus.setFont(font)
        self.button_leg5_front_minus.setObjectName("button_leg5_front_minus")

        self.button_leg5_middle_plus = QtWidgets.QPushButton(client)
        self.button_leg5_middle_plus.setGeometry(QtCore.QRect(1800, 420, 60, 30))
        self.button_leg5_middle_plus.setFont(font)
        self.button_leg5_middle_plus.setObjectName("button_leg5_middle_plus")

        self.button_leg5_middle_minus = QtWidgets.QPushButton(client)
        self.button_leg5_middle_minus.setGeometry(QtCore.QRect(1860, 420, 60, 30))
        self.button_leg5_middle_minus.setFont(font)
        self.button_leg5_middle_minus.setObjectName("button_leg5_middle_minus")

        self.button_leg5_back_plus = QtWidgets.QPushButton(client)
        self.button_leg5_back_plus.setGeometry(QtCore.QRect(1920, 450, 60, 30))
        self.button_leg5_back_plus.setFont(font)
        self.button_leg5_back_plus.setObjectName("button_leg5_back_plus")

        self.button_leg5_back_minus = QtWidgets.QPushButton(client)
        self.button_leg5_back_minus.setGeometry(QtCore.QRect(1980, 450, 60, 30))
        self.button_leg5_back_minus.setFont(font)
        self.button_leg5_back_minus.setObjectName("button_leg5_back_minus")

        #Leg 6
        self.button_leg6_front_plus = QtWidgets.QPushButton(client)
        self.button_leg6_front_plus.setGeometry(QtCore.QRect(1890, 60, 30, 60))
        self.button_leg6_front_plus.setFont(font)
        self.button_leg6_front_plus.setObjectName("button_leg6_front_plus")

        self.button_leg6_front_minus = QtWidgets.QPushButton(client)
        self.button_leg6_front_minus.setGeometry(QtCore.QRect(1890, 120, 30, 60))
        self.button_leg6_front_minus.setFont(font)
        self.button_leg6_front_minus.setObjectName("button_leg6_front_minus")

        self.button_leg6_middle_plus = QtWidgets.QPushButton(client)
        self.button_leg6_middle_plus.setGeometry(QtCore.QRect(1770, 180, 60, 30))
        self.button_leg6_middle_plus.setFont(font)
        self.button_leg6_middle_plus.setObjectName("button_leg6_middle_plus")

        self.button_leg6_middle_minus = QtWidgets.QPushButton(client)
        self.button_leg6_middle_minus.setGeometry(QtCore.QRect(1830, 180, 60, 30))
        self.button_leg6_middle_minus.setFont(font)
        self.button_leg6_middle_minus.setObjectName("button_leg6_middle_minus")

        self.button_leg6_back_plus = QtWidgets.QPushButton(client)
        self.button_leg6_back_plus.setGeometry(QtCore.QRect(1740, 210, 30, 60))
        self.button_leg6_back_plus.setFont(font)
        self.button_leg6_back_plus.setObjectName("button_leg6_back_plus")

        self.button_leg6_back_minus = QtWidgets.QPushButton(client)
        self.button_leg6_back_minus.setGeometry(QtCore.QRect(1740, 270, 30, 60))
        self.button_leg6_back_minus.setFont(font)
        self.button_leg6_back_minus.setObjectName("button_leg6_back_minus")

        # Displays controlls listed above.
        self.Video.raise_()
        self.label_head_title.raise_()
        self.slider_head.raise_()  
        self.label_head.raise_()
        self.slider_head_1.raise_()
        self.label_head_1.raise_()
        self.label_move_title.raise_()
        self.label_move_value.raise_()
        self.label_height.raise_()		
        self.slider_height.raise_()		
        self.label_height_value.raise_()	
        self.label_pane_title.raise_()	
        self.label_pane_value.raise_()
        self.label_twist_title.raise_()
        self.slider_twist.raise_()
        self.label_twist_value.raise_()
        self.label_tilt_title.raise_()
        self.label_tilt_value.raise_()
        self.Button_Connect.raise_()
        self.lineEdit_IP_Adress.raise_()
        self.Button_Calibration.raise_()	
        self.layoutWidget1.raise_()
        self.label_speed_title.raise_()
        self.slider_speed.raise_()
        self.label_speed.raise_()
        self.layoutWidget.raise_()
        self.Button_Buzzer.raise_()
        self.Button_Sonic.raise_()
        self.label_sonic.raise_()
        self.Button_LED.raise_()
        self.Button_IMU.raise_()
        self.Button_Relax.raise_()
        self.Button_Video.raise_()
        self.Button_Face_Recognition.raise_()
        self.Button_Face_ID.raise_()
        self.label_Load.raise_()
        self.progress_Power1.raise_()
        self.label_RasPi.raise_()
        self.progress_Power2.raise_()
        self.Button_Attack.raise_()
        self.Button_Dead.raise_()
        self.label_leg1_title.raise_()
        self.label_leg2_title.raise_()
        self.label_leg3_title.raise_()
        self.label_leg4_title.raise_()
        self.label_leg5_title.raise_()
        self.label_leg6_title.raise_()
        self.label_step_title.raise_()
        self.slider_step.raise_()
        self.label_step_value.raise_()
        self.label_leg1_front_value.raise_()
        self.label_leg1_middle_value.raise_()
        self.label_leg1_back_value.raise_()
        self.label_leg2_front_value.raise_()
        self.label_leg2_middle_value.raise_()
        self.label_leg2_back_value.raise_()
        self.label_leg3_front_value.raise_()
        self.label_leg3_middle_value.raise_()
        self.label_leg3_back_value.raise_()
        self.label_leg4_front_value.raise_()
        self.label_leg4_middle_value.raise_()
        self.label_leg4_back_value.raise_()
        self.label_leg5_front_value.raise_()
        self.label_leg5_middle_value.raise_()
        self.label_leg5_back_value.raise_()
        self.label_leg6_front_value.raise_()
        self.label_leg6_middle_value.raise_()
        self.label_leg6_back_value.raise_()
        self.button_leg1_front_plus.raise_()
        self.button_leg1_front_minus.raise_()
        self.button_leg1_middle_plus.raise_()
        self.button_leg1_middle_minus.raise_()
        self.button_leg1_back_plus.raise_()
        self.button_leg1_back_minus.raise_()
        self.button_leg2_front_plus.raise_()
        self.button_leg2_front_minus.raise_()
        self.button_leg2_middle_plus.raise_()
        self.button_leg2_middle_minus.raise_()
        self.button_leg2_back_plus.raise_()
        self.button_leg2_back_minus.raise_()
        self.button_leg3_front_plus.raise_()
        self.button_leg3_front_minus.raise_()
        self.button_leg3_middle_plus.raise_()
        self.button_leg3_middle_minus.raise_()
        self.button_leg3_back_plus.raise_()
        self.button_leg3_back_minus.raise_()
        self.button_leg4_front_plus.raise_()
        self.button_leg4_front_minus.raise_()
        self.button_leg4_middle_plus.raise_()
        self.button_leg4_middle_minus.raise_()
        self.button_leg4_back_plus.raise_()
        self.button_leg4_back_minus.raise_()
        self.button_leg5_front_plus.raise_()
        self.button_leg5_front_minus.raise_()
        self.button_leg5_middle_plus.raise_()
        self.button_leg5_middle_minus.raise_()
        self.button_leg5_back_plus.raise_()
        self.button_leg5_back_minus.raise_()
        self.button_leg6_front_plus.raise_()
        self.button_leg6_front_minus.raise_()
        self.button_leg6_middle_plus.raise_()
        self.button_leg6_middle_minus.raise_()
        self.button_leg6_back_plus.raise_()
        self.button_leg6_back_minus.raise_()

        # Puts on text in required places
        self.retranslateUi(client)
        QtCore.QMetaObject.connectSlotsByName(client)

        # Defines label texts
    def retranslateUi(self, client):
        _translate = QtCore.QCoreApplication.translate
        client.setWindowTitle(_translate("client", "Freenove Client for Hexapod by PR"))
        self.label_head_title.setText(_translate("client", "Head"))
        self.label_head.setText(_translate("client", "90"))
        self.label_head_1.setText(_translate("client", "90"))
        self.label_move_title.setText(_translate("client", "Move"))
        self.label_move_value.setText(_translate("client", "(0,0)"))
        self.label_height.setText(_translate("client", "Height"))
        self.label_height_value.setText(_translate("client", "0"))
        self.label_pane_title.setText(_translate("client", "Pane"))
        self.label_pane_value.setText(_translate("client", "(0,0)"))
        self.label_twist_title.setText(_translate("client", "Twist"))
        self.label_twist_value.setText(_translate("client", "0"))
        self.label_tilt_title.setText(_translate("client", "Tilt"))
        self.label_tilt_value.setText(_translate("client", "(0,0)"))
        self.Button_Connect.setText(_translate("client", "Connect"))
        self.lineEdit_IP_Adress.setText(_translate("client", "x.x.x.x"))
        self.Button_Calibration.setText(_translate("client", "Calibration"))
        self.ButtonGaitMode1.setText(_translate("client", "Run"))
        self.ButtonGaitMode2.setText(_translate("client", "Walk"))
        self.label_speed_title.setText(_translate("client", "Speed"))
        self.label_speed.setText(_translate("client", "8"))
        self.ButtonActionMode1.setText(_translate("client", "Strafe"))
        self.ButtonActionMode2.setText(_translate("client", "Turn"))
        self.Button_Buzzer.setText(_translate("client", "Buzzer"))
        self.Button_Sonic.setText(_translate("client", "Sonar"))
        self.label_sonic.setText(_translate("client", "Obstacle: 0cm"))
        self.Button_LED.setText(_translate("client", "LED"))
        self.Button_IMU.setText(_translate("client", "Balance"))
        self.Button_Relax.setText(_translate("client", "Relax"))
        self.Button_Video.setText(_translate("client", "Open Video"))
        self.Button_Face_Recognition.setText(_translate("client", "Face Recog"))
        self.Button_Face_ID.setText(_translate("client", "Face ID"))
        self.label_Load.setText(_translate("client", "Load"))
        self.label_RasPi.setText(_translate("client", "RasPi"))
        self.Button_Attack.setText(_translate("client", "Attack"))
        self.Button_Dead.setText(_translate("client", "Dead"))
        self.label_leg1_title.setText(_translate("client", "Leg 1"))
        self.label_leg2_title.setText(_translate("client", "Leg 2"))
        self.label_leg3_title.setText(_translate("client", "Leg 3"))
        self.label_leg4_title.setText(_translate("client", "Leg 4"))
        self.label_leg5_title.setText(_translate("client", "Leg 5"))
        self.label_leg6_title.setText(_translate("client", "Leg 6"))
        self.label_step_title.setText(_translate("client", "Step"))
        self.label_step_value.setText(_translate("client", "5"))
        self.label_leg1_front_value.setText(_translate("client", "S: 13"))
        self.label_leg1_middle_value.setText(_translate("client", "S: 14"))
        self.label_leg1_back_value.setText(_translate("client", "S: 15"))
        self.label_leg2_front_value.setText(_translate("client", "S: 10"))
        self.label_leg2_middle_value.setText(_translate("client", "S: 11"))
        self.label_leg2_back_value.setText(_translate("client", "S: 12"))
        self.label_leg3_front_value.setText(_translate("client", "S: 31"))
        self.label_leg3_middle_value.setText(_translate("client", "S: 8"))
        self.label_leg3_back_value.setText(_translate("client", "S: 9"))
        self.label_leg4_front_value.setText(_translate("client", "S: 27"))
        self.label_leg4_middle_value.setText(_translate("client", "S: 23"))
        self.label_leg4_back_value.setText(_translate("client", "S: 22"))
        self.label_leg5_front_value.setText(_translate("client", "S: 21"))
        self.label_leg5_middle_value.setText(_translate("client", "S: 20"))
        self.label_leg5_back_value.setText(_translate("client", "S: 19"))
        self.label_leg6_front_value.setText(_translate("client", "S: 18"))
        self.label_leg6_middle_value.setText(_translate("client", "S: 17"))
        self.label_leg6_back_value.setText(_translate("client", "S: 16"))
        self.button_leg1_front_plus.setText(_translate("client", "+"))
        self.button_leg1_front_minus.setText(_translate("client", "-"))
        self.button_leg1_middle_plus.setText(_translate("client", "+"))
        self.button_leg1_middle_minus.setText(_translate("client", "-"))
        self.button_leg1_back_plus.setText(_translate("client", "+"))
        self.button_leg1_back_minus.setText(_translate("client", "-"))
        self.button_leg2_front_plus.setText(_translate("client", "+"))
        self.button_leg2_front_minus.setText(_translate("client", "-"))
        self.button_leg2_middle_plus.setText(_translate("client", "+"))
        self.button_leg2_middle_minus.setText(_translate("client", "-"))
        self.button_leg2_back_plus.setText(_translate("client", "+"))
        self.button_leg2_back_minus.setText(_translate("client", "-"))
        self.button_leg3_front_plus.setText(_translate("client", "+"))
        self.button_leg3_front_minus.setText(_translate("client", "-"))
        self.button_leg3_middle_plus.setText(_translate("client", "+"))
        self.button_leg3_middle_minus.setText(_translate("client", "-"))
        self.button_leg3_back_plus.setText(_translate("client", "+"))
        self.button_leg3_back_minus.setText(_translate("client", "-"))
        self.button_leg4_front_plus.setText(_translate("client", "+"))
        self.button_leg4_front_minus.setText(_translate("client", "-"))
        self.button_leg4_middle_plus.setText(_translate("client", "+"))
        self.button_leg4_middle_minus.setText(_translate("client", "-"))
        self.button_leg4_back_plus.setText(_translate("client", "+"))
        self.button_leg4_back_minus.setText(_translate("client", "-"))
        self.button_leg5_front_plus.setText(_translate("client", "+"))
        self.button_leg5_front_minus.setText(_translate("client", "-"))
        self.button_leg5_middle_plus.setText(_translate("client", "+"))
        self.button_leg5_middle_minus.setText(_translate("client", "-"))
        self.button_leg5_back_plus.setText(_translate("client", "+"))
        self.button_leg5_back_minus.setText(_translate("client", "-"))
        self.button_leg6_front_plus.setText(_translate("client", "+"))
        self.button_leg6_front_minus.setText(_translate("client", "-"))
        self.button_leg6_middle_plus.setText(_translate("client", "+"))
        self.button_leg6_middle_minus.setText(_translate("client", "-"))
        self.button_leg6_back_plus.setText(_translate("client", "+"))
        self.button_leg6_back_minus.setText(_translate("client", "-"))